- hosts: Client
  become: yes
  
  tasks:
   - name: install pip
     apt:
       name: python-pip
       state: present

   - name: Install prerequisites
     apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
      state: present
      
   - name: Add Docker GPG key
     apt_key: url=https://download.docker.com/linux/ubuntu/gpg

   - name: Add Docker APT repository
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

   - name : install docker
     apt:
       name: docker-ce
       state: present

   - name: install docker module
     pip: name=docker-py

  tasks:
    - name: Pull docker image
      shell: docker pull bharathuppiretla/petclinic


    - name: Run docker container
      shell: docker run -itd -p 8083:8080  bharathuppiretla/petclinic
     
